_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
adversary_hidden_size:
    value: 32
batch_size:
    value: 64
cols_to_hide:
    value:
        - 4
debug:
    value: false
debug_port:
    value: 42020
defacto_data_raw_path:
    value: ./data/
ds_cache:
    value: .cache/pykalpkg_ds.csv
episode_gap:
    value: 3
episode_length:
    value: 32
epochs:
    value: 1000
eval_interval:
    value: 100
eval_size:
    value: 4
first_n_states:
    value: 7
kl_dig_hypr:
    value: 0.1
lr:
    value: 0.01
no_autoindent:
    value: null
padding_value:
    value: -1
rnn_hidden_size:
    value: 15
rnn_num_layers:
    value: 2
saveplot_dest:
    value: ./figures/pykalman_transformer/
seed:
    value: 0
shuffle:
    value: true
splits:
    value:
        test_split: 0
        train_split: 0.8
        val_split: 0.2
vae_ds_cache:
    value: .cache/pykalpkg_vaeds.csv
vae_hidden_size:
    value: 32
vae_latent_size:
    value: 32
wandb:
    value: true
